# Stage 1: Build the React application
FROM node:lts-alpine AS build
WORKDIR /app
COPY ./kiosk .
RUN source env/bin/activate && npm ci && npm run build

# Stage 2: Serve the built application with Nginx
FROM nginx:latest AS prod
COPY --from=build /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf

CMD ["nginx"]